# Generated by Django 3.2.3 on 2021-06-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idNombre', models.IntegerField(primary_key=True, serialize=False, verbose_name='IdNombre')),
                ('correoElectronico', models.CharField(max_length=100, verbose_name='CorreoElectronico')),
                ('nombreContacto', models.CharField(max_length=100, verbose_name='Nombre')),
                ('numeroTelefono', models.IntegerField(verbose_name='NumeroTelefono')),
                ('mensajeContacto', models.CharField(max_length=500, verbose_name='Mensaje')),
            ],
        ),
    ]
